apiVersion: v1
kind: Namespace
metadata:
  name: master-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: master-label
  name: master-ubuntu
  namespace: master-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-label
  template:
    metadata:
      labels:
        app: master-label
    spec:
      containers:
        - name: master-ubuntu
          image: master-ubuntu:0.0
          resources: {}
          ports:
            - name: nginx-port
              containerPort: 80
            - name: ssh-port
              containerPort: 22
            - name: webssh-port
              containerPort: 8888
            - name: server-port
              containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: master-ubuntu-svc
  namespace: master-ns
spec:
  ports:
    - name: http
      port: 81
      targetPort: nginx-port
    - name: ssh
      port: 22
      targetPort: ssh-port
    - name: webssh
      port: 8888
      targetPort: webssh-port
    - name: server
      port: 8001
      targetPort: server-port
  selector:
    app: master-label
  type: LoadBalancer
---

