apiVersion: v1
kind: Pod
metadata:
  name: student-ubuntu
  namespace: student-ns
  labels:
    app: student-label
spec:
  containers:
    - name: student-ubuntu
      image: ryann3/student-ubuntu:5.0
      ports:
        - name: nginx-port
          containerPort: 80
        - name: ssh-port
          containerPort: 22
        - name: webssh-port
          containerPort: 8888
        - name: server-port
          containerPort: 8001
      resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: student-ubuntu-svc
  namespace: student-ns
spec:
  ports:
    - name: http
      port: 81
      targetPort: nginx-port
    - name: webssh
      port: 8888
      targetPort: webssh-port
    - name: server
      port: 8001
      targetPort: server-port
  selector:
    app: student-label
  type: LoadBalancer
