apiVersion: v1
kind: Namespace
metadata:
  name: control-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: access-to-apiserver-sa
  namespace: control-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-to-apiserver-cr
  namespace: control-ns
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - nodes
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-to-apiserver-crb
subjects:
  - kind: ServiceAccount
    name: access-to-apiserver-sa
    namespace: control-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: access-to-apiserver-cr
---
apiVersion: v1
kind: Pod
metadata:
  name: control-ubuntu
  namespace: control-ns
  labels:
    app: control-label
spec:
  containers:
    - name: control-ubuntu
      image: control-ubuntu:1.2
      ports:
        - name: nginx-port
          containerPort: 80
        - name: ssh-port
          containerPort: 22
        - name: server-port
          containerPort: 8003
        - name: webssh-port
          containerPort: 8886
      resources: {}
  serviceAccountName: access-to-apiserver-sa
---
apiVersion: v1
kind: Service
metadata:
  name: control-ubuntu-svc
  namespace: control-ns
spec:
  ports:
    - name: http
      port: 81
      targetPort: nginx-port
    - name: ssh
      port: 22
      targetPort: ssh-port
    - name: webssh
      port: 8886
    - name: server
      port: 8003
      targetPort: server-port
  selector:
    app: control-label
  type: LoadBalancer
