apiVersion: v1
kind: Namespace
metadata:
  name: control-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: professor-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: student-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: access-to-apiserver-sa
  namespace: control-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-to-apiserver-cr
  namespace: control-ns
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
      - services
      - nodes
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-to-apiserver-crb
subjects:
  - kind: ServiceAccount
    name: access-to-apiserver-sa
    namespace: control-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: access-to-apiserver-cr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-ubuntu
  namespace: control-ns
  labels:
    app: control-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-label
  template:
    metadata:
      labels:
        app: control-label
    spec:
      containers:
        - name: control-ubuntu
          image: ryann3/control-ubuntu:5.0
          imagePullPolicy: Always
          ports:
            - name: nginx-port
              containerPort: 80
            - name: ssh-port
              containerPort: 22
            - name: server-port
              containerPort: 8003
            - name: webssh-port
              containerPort: 8886
          resources: {}
      serviceAccountName: access-to-apiserver-sa
---
apiVersion: v1
kind: Service
metadata:
  name: control-ubuntu-svc
  namespace: control-ns
spec:
  ports:
    - name: http
      port: 81
      targetPort: nginx-port
    - name: webssh
      port: 8886
      nodePort: 30000
    - name: server
      port: 8003
      targetPort: server-port
      nodePort: 30001
  selector:
    app: control-label
  type: NodePort
