apiVersion: apps/v1
kind: Deployment
metadata:
  name: professor-{{ ID }}
  namespace: professor-ns
  labels:
    app: professor-label-{{ ID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: professor-label-{{ ID }}
  template:
    metadata:
      labels:
        app: professor-label-{{ ID }}
    spec:
      containers:
        - name: professor-{{ ID }}
          image: ryann3/professor-ubuntu:6.0
          imagePullPolicy: Always
          ports:
            - name: nginx-port
              containerPort: 80
            - name: ssh-port
              containerPort: 22
            - name: webssh-port
              containerPort: 8888
            - name: server-port
              containerPort: 8001
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: professor-{{ ID }}-svc
  namespace: professor-ns
spec:
  ports:
    - name: http
      port: 81
      targetPort: nginx-port
    - name: webssh
      port: { PORT }
      targetPort: webssh-port
      nodePort: { WEB_NODE_PORT }
    - name: server
      port: { API_PORT }
      targetPort: server-port
      nodePort: { APP_NODE_PORT }
  selector:
    app: professor-label-{{ ID }}
  type: NodePort
