name: Docker Image CI(Student server)

on:
  push:
    paths:
      - "resources/images/student-ubuntu/**"
    branches:
      - "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./resources/images/student-ubuntu/
          file: ./resources/images/student-ubuntu/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ryann3/student-ubuntu:7.0
